#!/bin/bash
#requires pakextract, bsputil, optipng, and qpakman
# git source: https://github.com/ciscon/random/blob/master/quake-scripts/quake_convert_textures-hq8x.sh

#magnify method: eagle2X, eagle3X, eagle3XB, epb2X, fish2X, hq2X, scale2X, scale3X, xbr2X
method="scale2X"
ops="-magnify -magnify -magnify"
fil="scale8x.pk3"
np="0"

if [[ "$1" != "0" || "$1" == "-h" || "$1" == "--help" ]]; then 

	if [[ "$1" == "-h" || "$1" == "--help" ]]; then

		echo "hq8x"
		echo
		echo "		0 -np -m -o -f [filespec]"
		echo
		echo "	0 - acknowledge tmp dir ops - my reminder"
		echo "	-np - ignore any .pak files found"
		echo "	-m {select method from list}"
		echo "methods:"
		echo "	eagle2X, eagle3X, eagle3XB, epb2X, fish2X, hq2X, scale2X, scale3X, xbr2X"
		echo "	default = scale2x"
		echo "	-o {specify operation}"
		echo "operation"
		echo "	default = -magnify -magnify -magnify"
		echo
		echo "	-f [filspec] - write this zipfile"
		echo "	default: scale8x.pk3"
		echo
		echo "	pak files: place in tmp dir, run $(basename $0) without '-np' - uses unpacked maps dir with maps"
		echo "	map files: place *.bsp in tmp dir, run $(basename $0)"
		echo "	wad files: place *.wad in tmp dir, run $(basename $0)"
		echo "	png files: place *.png in tmp dir, run $(basename $0)"
		echo
	else
		echo "--- you must operate in tmp folders"

		if [[ ! -f pak0.pak ]];then
			echo "no pak file"
		fi
	fi
else

# while loop proc all parms but final filespec for zip file

  while [[ "$1" != "" ]]; do

#	if [[  "$1" == "0" ]]; then shift; fi
 	if [[  "$1" == "-np" ]]; then np="1"; fi

	if [[ "$1" == "-m" ]]; then

		shift
		method="$1"

	fi

        if [[ "$1" == "-o" ]]; then

                shift
                ops="$1"

        fi

	if [[ "$1" == "-f" ]]; then

		shift
		fil="$1"

	fi

	shift
  done

# if none of the unpack / convert ops set this to 1, script will exit with no converts
set nop="0"

# 1 time op to move an existing map dir if unpacking
set mvd="1"

if [[ "$np" != "1" ]]; then

for i in *.pak;do

# move an exiting map dir - one time only, the unpack will make a new map dir
	if [[ -d maps && "$mvd" == "1" ]];then

		mvd="0"
	        mv -i maps maps.0
	fi

	if [[ -f "$i" ]]; then pakextract $i; fi;
	
done 2> /dev/null

fi



cd maps 2> /dev/null

#other bsps?
#cp /path/to/other/bsps/*.bsp .

for i in *.bsp;do if [[ -f "$i" ]]; then nop="1";bsputil --extract-textures $i;fi;done 2> /dev/null
for i in *.wad;do if [[ -f "$i" ]]; then nop="1";qpakman -f -e "$i";fi;done 2> /dev/null

#greyscale?
#for i in *.png;do convert $i -set colorspace Gray -separate -average $i;done 

for i in *.png;do 
	#hq8x
#	convert $i -magnify -magnify -magnify $i
	if [[ -f "$i" ]]; then nop="1"; convert $i -define magnify:method=$method $ops $i; fi
done 

if [[ "$nop" == "1" ]]; then

if [[ -d textures ]];then
#	rm -rf textures
	mv textures textures.0
fi
mkdir textures 
mv *.png textures 
cd textures

#optimize pngs
optipng -strip all *.png

#fix names
#		noticed some rename issues with some special texs -- these:
#Unknown option: a
#Usage: rename [-v] [-n] [-f] perlexpr [filenames]
#Unknown option: 0
#Unknown option: 0
#

rename 's/plus_/+/' *.png
rename 's/star_/#/' *.png
rename 's/_fbr//' *.png

cd ..

zip -r ../$fil textures 

else

	echo hq8x - no operation performed...

fi
fi
